version: 2.1
executors:
  vagrat_executor:
    machine:
      image: ubuntu-2204:2023.04.2
    environment:
      VAGRANT_VERSION: 2.3.6
      LINUX_RELEASE: jammy
      VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1

jobs:
  build:
    executor: vagrat_executor
    steps:
      - checkout
      - run:
          name: Installing the Vagrant and Virtualbox
          command: |
            cat /etc/*release
            cd ./scripts/
            . circleci_prereqs.sh
            install_virtualbox
            install_vagrant
      - run:
          name: Building the Vagrant box
          command: |
            cd ./scripts/
            . vagrant_box_release.sh
            build_vagrant_box
      - persist_to_workspace:
          root: .
          paths:
            - scripts/vagrant_box_release.sh
            - scripts/circleci_prereqs.sh
            - molecule.box
            - release_version

  release:
    executor: vagrat_executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Installing Vagrant
          command: |
            cd ./scripts/
            . circleci_prereqs.sh
            install_vagrant
      - run:
          name: Publishing the Vagrant box
          command: |
            cd ./scripts/
            . vagrant_box_release.sh
            publish_vagrant_box

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          context: Vagrant
      - release:
          requires:
            - build
          context: Vagrant
